// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import GameController from "controllers/game_controller"
application.register("game", GameController)
