default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: your_db_username
  password: your_db_password

development:
  <<: *default
  database: tic_tac_toe_game_development

test:
  <<: *default
  database: tic_tac_toe_game_test

production:
  <<: *default
  database: tic_tac_toe_game_production
  username: tic_tac_toe_game
  password: <%= ENV['TIC_TAC_TOE_GAME_DATABASE_PASSWORD'] %>
